# Generated by Django 5.2 on 2025-05-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
