# Generated by Django 5.2 on 2025-05-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0003_alter_floor_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='created_at',
        ),
    ]
