# Generated by Django 5.2 on 2025-05-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_id', models.CharField(max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='floor.floor')),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
    ]
