# Generated by Django 5.2 on 2025-05-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
