# Generated by Django 5.2 on 2025-05-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehouse_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='created_at',
        ),
    ]
