# Generated by Django 5.2 on 2025-05-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
        ('tower', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('total_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TileStockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.floor')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.tileshipment')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tower.tower')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.AddField(
            model_name='tileshipment',
            name='tile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.tiletype'),
        ),
    ]
