# Generated by Django 5.2 on 2025-05-01 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tower', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TileStackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('tile_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('stacking_date', models.DateField()),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('remaining_count', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tile_images/')),
                ('warehouse_name', models.CharField(max_length=100)),
                ('floor_number', models.PositiveIntegerField()),
                ('tower_identifier', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tile_entries', to=settings.AUTH_USER_MODEL)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_stacks', to='tower.tower')),
            ],
        ),
    ]
