# Generated by Django 5.2.3 on 2025-06-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='shipment_date',
            new_name='shipment_arrival_date',
        ),
    ]
