# Generated by Django 5.2.3 on 2025-06-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together={('tile_name', 'brand', 'size')},
        ),
    ]
